/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QRContentType = IDL.Variant({
  'sms' : IDL.Null,
  'url' : IDL.Null,
  'contactInfo' : IDL.Null,
  'text' : IDL.Null,
  'wifi' : IDL.Null,
  'email' : IDL.Null,
  'event' : IDL.Null,
  'phoneNumber' : IDL.Null,
  'geoLocation' : IDL.Null,
});
export const Time = IDL.Int;
export const QRCodeData = IDL.Record({
  'backgroundColor' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'contentType' : QRContentType,
  'createdAt' : Time,
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Nat),
  'lastModified' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQRCodeHistory' : IDL.Func([], [IDL.Vec(QRCodeData)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveQRCode' : IDL.Func([QRCodeData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QRContentType = IDL.Variant({
    'sms' : IDL.Null,
    'url' : IDL.Null,
    'contactInfo' : IDL.Null,
    'text' : IDL.Null,
    'wifi' : IDL.Null,
    'email' : IDL.Null,
    'event' : IDL.Null,
    'phoneNumber' : IDL.Null,
    'geoLocation' : IDL.Null,
  });
  const Time = IDL.Int;
  const QRCodeData = IDL.Record({
    'backgroundColor' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'contentType' : QRContentType,
    'createdAt' : Time,
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Nat),
    'lastModified' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQRCodeHistory' : IDL.Func([], [IDL.Vec(QRCodeData)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveQRCode' : IDL.Func([QRCodeData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };